### ISSUE TITLE
Problem with "Adopting oldest dog" test

### ISSUE THREAD

**Issue by levia15** [Lprob1/Assignment3_COMP250#1]
Hey I noticed for the "Adopting oldest dog" test you are actually just adopting the root, which isn't necessarily the oldest dog. Just a heads up in case you actually wanted to test adopting the oldest dog. Thanks for sharing these tests though!

**Comment by Lprob1** [comment]
Hi! That's a good catch, I wrote oldest dog but I meant the one that's been at the shelter for the longest! Sorry for the confusion

**Comment by levia15** [comment]
Oh that makes sense. Thanks!
